/**
 * @file   main.c
 * @author Michel Catudal
 * @date   28 May 2022
 * @version 0.1
 * @brief  main app
 *
*/
/***********************************************************************************************************************
* Code based on code generated by Applilet4 for RL78/G11 and IAR Systems iccrl78
* Copyright (C) 2016, 2021 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/
/***********************************************************************************************************************
Includes
***********************************************************************************************************************/
#include "r_cg_macrodriver.h"
#include "r_cg_cgc.h"
#include "r_cg_pfdl.h"
#include "r_cg_port.h"
#include "r_cg_tau.h"
#include "r_cg_sau.h"
#include "r_cg_adc.h"
#include "r_cg_intp.h"
#include "r_cg_userdefine.h"
#include "lin.h"
#include "Rtksched.h"

/***********************************************************************************************************************
Global variables and functions
***********************************************************************************************************************/

/* Set option bytes */
#pragma location = "OPTBYTE"
__root const uint8_t opbyte0 = 0xEFU;
#pragma location = "OPTBYTE"
__root const uint8_t opbyte1 = 0xFFU;
#pragma location = "OPTBYTE"
__root const uint8_t opbyte2 = 0xF0U;
#pragma location = "OPTBYTE"
__root const uint8_t opbyte3 = 0x85U;

/* Set security ID */
#pragma location = "SECUID"
__root const uint8_t secuid[10] =
    {0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U, 0x00U};

/***********************************************************************************************************************
* Function Name: main
* Description  : This function implements main function.
* Arguments    : None
* Return Value : None
***********************************************************************************************************************/
void main(void)
{
    R_TAU0_Channel0_Start();
    R_CSI11_Start();
//    R_UART0_Start();
//    Init_LIN_HeaderRx();
    EI();

    while (1U)
    {
        vRtk_eScheduler_Tsk();
    }
}
