/**
 * @file   r_cg_port.c
 * @author Michel Catudal
 * @date   23 June 2022
 * @version 0.1
 * @brief  pfdl driver
 *
*/

/***********************************************************************************************************************
* Code based on code generated by Applilet3 for RL78/G14 and IAR Systems iccrl78
* Copyright (C) 2011, 2021 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/
/***********************************************************************************************************************
Includes
***********************************************************************************************************************/
#include "system.h"
#include "r_cg_port.h"

/***********************************************************************************************************************
Global variables and functions
***********************************************************************************************************************/

/***********************************************************************************************************************
* Function Name: R_PORT_Create
* Description  : This function initializes the Port I/O.
* Arguments    : None
* Return Value : None
***********************************************************************************************************************/
void R_PORT_Create(void)
{
    P6 = _00_Pn2_OUTPUT_0;
    PMC0 = _00_PMCn0_DI_ON | _00_PMCn1_DI_ON | _FC_PMC0_DEFAULT;
    PMC1 = _04_PMCn2_NOT_USE | _08_PMCn3_NOT_USE | _00_PMCn6_DI_ON | _80_PMCn7_NOT_USE;
    PM0 = _01_PMn0_MODE_INPUT | _02_PMn1_MODE_INPUT | _FC_PM0_DEFAULT;
    PM1 = _01_PMn0_NOT_USE | _02_PMn1_NOT_USE | _04_PMn2_NOT_USE | _08_PMn3_NOT_USE | _10_PMn4_NOT_USE |
          _20_PMn5_NOT_USE | _40_PMn6_MODE_INPUT | _80_PMn7_NOT_USE;
    PM6 = _01_PMn0_NOT_USE | _02_PMn1_NOT_USE | _00_PMn2_MODE_OUTPUT | _F8_PM6_DEFAULT;
}

