/**
 * @file   r_cg_cgc.c
 * @author Michel Catudal
 * @date   3 July 2022
 * @brief  CAN interface
 *
*/
/***********************************************************************************************************************
* Code based on code generated by Applilet3 for RL78/G14 and IAR Systems iccrl78
* Copyright (C) 2011, 2021 Renesas Electronics Corporation. All rights reserved.
***********************************************************************************************************************/

/***********************************************************************************************************************
Includes
***********************************************************************************************************************/
#include "system.h"
#include "r_cg_cgc.h"

/***********************************************************************************************************************
* Function Name: R_CGC_Create
* Description  : This function initializes the clock generator.
* Arguments    : None
* Return Value : None
***********************************************************************************************************************/
void R_CGC_Create(void)
{
    /* Set fMX */
    CMC = _00_CGC_HISYS_PORT | _00_CGC_SYSOSC_DEFAULT;
    MSTOP = 1U;
    /* Set fMAIN */
    MCM0 = 0U;
    OSMC = _10_CGC_RTC_CLK_FIL;
    /* Set fIH */
    HIOSTOP = 0U;
}

/***********************************************************************************************************************
* Function Name: R_CGC_Get_ResetSource
* Description  : This function process of Reset.
* Arguments    : None
* Return Value : None
***********************************************************************************************************************/
void R_CGC_Get_ResetSource(void)
{
    uint8_t reset_flag = RESF;
    /* Start user code. Do not edit comment generated here */
    /* End user code. Do not edit comment generated here */
}

